version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: PostgresContainer
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 271024
    ports:
      - "5432:5432"

  app:
    image: dockerdemo # Replace with your actual Spring Boot image
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 271024
